export const USD_TO_IDR = 16000;

export const EXCHANGE_RATES_USD = {
  ETH: 2629,
  wBTC: 107157,
  PEPE: 0.00001354,
};

export const EXCHANGE_RATES_IDR = {
  ETH: EXCHANGE_RATES_USD.ETH * USD_TO_IDR,
  wBTC: EXCHANGE_RATES_USD.wBTC * USD_TO_IDR,
  PEPE: EXCHANGE_RATES_USD.PEPE * USD_TO_IDR,
};

export const EXCHANGE_RATES = {
  USD: EXCHANGE_RATES_USD,
  IDR: EXCHANGE_RATES_IDR,
};
